version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.3-node
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USERNAME: 'root'
          DB_PASSWORD: ''
      - image: circleci/mysql:5.7
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: bundler
          command: |  
            gem install bundler -v 2.2.21
            bundle update
            bundle install
      - run:
          name: データベース
          command: |
            dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
            rails db:create
            rails db:schema:load
      - run:
          name: rubocop実行
          command: bundle exec rubocop
      - run:
          name: テスト実行
          command: bundle exec rspec